name: kavid
description: "proyecto base KAVID"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # === Usuario + Splash + Vista General ===
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  intl: ^0.19.0

  # === Gastos diarios (Tema 6) ===
  google_mlkit_text_recognition: ^0.14.0
  uuid: ^4.4.2

  # === OCR robusta + preprocesado + cámara propia ===
  flutter_exif_rotation: ^0.5.2
  image: ^4.2.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1

  # === Calendario ===
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#FF9800"
