name: kavid
description: "proyecto base KAVID"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # === Usuario + Splash + Vista General ===
  image_picker: ^1.1.2           # seleccionar foto (cámara/galería)
  shared_preferences: ^2.2.3     # guardar nombre/correo/teléfono
  path_provider: ^2.1.4          # guardar imagen en documentos de la app
  intl: ^0.19.0                  # fechas y formatos en español (Vista General + Gastos)

  # === Gastos diarios (Tema 6) ===
  google_mlkit_text_recognition: ^0.14.0  # OCR para tickets
  uuid: ^4.4.2                            # generar IDs únicas para los gastos

  # === Calendario (Tema 6) ===
  table_calendar: ^3.0.9        # mostrar calendario personalizado

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#FF9800"
